Add missing dependency on qt_gui_py_common
This fixes the following error on Noetic:

    RosPluginProvider.load(frame_editor/Frame Editor) exception raised in __builtin__.__import__(frame_editor.rqt_editor, [FrameEditorGUI]):
    Traceback (most recent call last):
      File "/opt/ros/noetic/lib/python3/dist-packages/rqt_gui/ros_plugin_provider.py", line 79, in load
        module = __builtin__.__import__(
      File "[...]/rqt_frame_editor_plugin/frame_editor/src/frame_editor/rqt_editor.py", line 11, in <module>
        from qt_gui_py_common.worker_thread import WorkerThread
    ModuleNotFoundError: No module named 'qt_gui_py_common'